# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Buildcaptain < Formula
  desc "CLI and MCP gateway for the BuildCaptain macOS Jenkins app"
  homepage "https://buildcaptain.dev"
  version "26.8.1"
  license "MIT"
  depends_on :macos

  url "https://github.com/inuali/buildcaptain-cli/releases/download/v26.8.1/buildcaptain_26.8.1_darwin_all.tar.gz"
  sha256 "1df4dc7d3ec09cd66075b327ed97992c8f1ba769089170f06f357e6f6802a67d"

  define_method(:install) do
    bin.install "buildcaptain"
  end

  test do
    system "#{bin}/buildcaptain", "version"
  end
end
