# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubegate < Formula
  desc "Human approval for AI-driven Kubernetes changes — the KubeGate CLI and MCP server"
  homepage "https://github.com/inuali/kubegate-cli"
  version "26.9.1"
  license "MIT"
  depends_on :macos

  url "https://github.com/inuali/kubegate-cli/releases/download/v26.9.1/kubegate_26.9.1_darwin_all.tar.gz"
  sha256 "e2d8775c26932f9e56b469909aeea52398257953a39ce51121cc7d62cca4fe26"

  define_method(:install) do
    bin.install "kubegate"
  end

  test do
    system "#{bin}/kubegate", "version"
  end
end
