# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubegate < Formula
  desc "Human approval for AI-driven Kubernetes changes — the KubeGate CLI and MCP server"
  homepage "https://github.com/inuali/kubegate-cli"
  version "26.9.3"
  license "MIT"
  depends_on :macos

  url "https://github.com/inuali/kubegate-cli/releases/download/v26.9.3/kubegate_26.9.3_darwin_all.tar.gz"
  sha256 "6b59a190ae5b5fa8cecd58cc3f69a1e4cfc3bf0d2599a41ea34284705737e207"

  define_method(:install) do
    bin.install "kubegate"
  end

  test do
    system "#{bin}/kubegate", "version"
  end
end
