# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubegate < Formula
  desc "Human approval for AI-driven Kubernetes changes — the KubeGate CLI and MCP server"
  homepage "https://github.com/inuali/kubegate-cli"
  version "26.9.2"
  license "MIT"
  depends_on :macos

  url "https://github.com/inuali/kubegate-cli/releases/download/v26.9.2/kubegate_26.9.2_darwin_all.tar.gz"
  sha256 "54214251f98b8ee2c407f7c131ed71aff69aed5ba028d18b95631716438982db"

  define_method(:install) do
    bin.install "kubegate"
  end

  test do
    system "#{bin}/kubegate", "version"
  end
end
